### ISSUE TITLE
Add binaries/releases to releases on GitHub

### ISSUE THREAD

**Issue by DerekTurtleRoe** [OBattler/PCem-X#34]
Exactly what the title says, not much else to say. :smile:

**Comment by DrFrankenstein** [comment]
I'm just going to leave this here since it's not exactly clear, but the binaries for each commit can be found by clicking the [![Build Status](http://citadel.rol.im:8080/job/PCem-X/badge/icon)](http://citadel.rol.im:8080/job/PCem-X/) badge on the repo's readme (under Last Successful Artifacts). If releases aren't going to be added on GitHub, perhaps that the readme could be clarified on that subject.

**Comment by DerekTurtleRoe** [comment]
@DrFrankenstein Since the links are dead, the image doesn't load on some browsers, and this has been replaced by 86Box, I think I will close this. 😃
